fear readme: Add docs and license
userver-framework/uservice-dynconf pull request #11
Opened 2022-05-28 14:26 UTC by alexiprof

Add docs and license

2022-05-28 14:50 UTC, apolukhin requested changes

2022-05-28 14:50 UTC, apolukhin commented on README.md
> +## Run uservice-config
У сервиса другое имя

2022-05-28 14:50 UTC, apolukhin commented on README.md
> +To create your own userver-based service follow the following steps:
```suggestion
```

2022-05-28 14:50 UTC, apolukhin commented on README.md
> +2. Run postgresql (support Postgres-10+)
кажется 12 - минималка, но это не точно

2022-05-28 14:50 UTC, apolukhin commented on README.md
> +## Using this another userver microservices
Неопнятно что написано

2022-05-28 14:50 UTC, apolukhin commented on README.md
> +7. Run `/usr/local/bin/uservice-dynconf --config /usr/local/etc/uservice-dynconf/config_vars.yaml`
Длинноватая инструкция и сложная. Тут надо упрощать, особенно непонятно чот делать в шаге 3 и 2

2022-05-28 14:50 UTC, apolukhin commented on README.md
> +            config-url: http://localhost:8083
Нужно наверное сделать на примере service_template - сделать ссылку на кусок конфигурации, куда вставлять новые параметры

2022-05-28 14:50 UTC, apolukhin commented on README.md
> +## Http api
```suggestion
## HTTP API
```

2022-05-28 14:50 UTC, apolukhin commented on README.md
> +Http api uservice-dynconf described in OpenAPI format in [file](https://github.com/userver-framework/uservice-dynconf/blob/develop/docs/api/api.yaml)
```suggestion
HTTP REST API of the uservice-dynconf is described in OpenAPI format in [file](https://github.com/userver-framework/uservice-dynconf/blob/develop/docs/api/api.yaml)
```

2022-05-28 14:50 UTC, apolukhin commented on README.md
> +Makefile contains typicaly useful targets for development:
```suggestion
Makefile contains useful targets for development:
```

2022-05-28 14:50 UTC, apolukhin commented on README.md
> +The original template is distributed under the [Apache-2.0 License](https://github.com/userver-framework/userver/blob/develop/LICENSE) and [CLA](https://github.com/userver-framework/userver/blob/deve
```suggestion
# License

Distributed under the [Apache-2.0 License](https://github.com/userver-framework/userver-dynconf/blob/develop/LICENSE) with the [CLA](https://github.com/userver-framework/userver-dynconf/blob/develop/CONTRIBUTING.md).
```

2022-05-30 08:40 UTC, alexiprof commented
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/

2022-05-30 10:01 UTC, apolukhin requested changes

2022-05-30 10:01 UTC, apolukhin commented on README.md
> +In [`file static_configs.yaml`](https://github.com/userver-framework/service_template/blob/develop/configs/static_config.yaml.in#L22) set:
```suggestion
In [file `static_configs.yaml`](https://github.com/userver-framework/service_template/blob/develop/configs/static_config.yaml.in#L22) of the microservice add the following lines to connect and retrieve configurations from the `uservice-dynconf`:
```

2022-05-30 10:01 UTC, apolukhin commented on README.md
> +            config-url: http://localhost:8083
```suggestion
            config-url: http://localhost:8083  # uservice-dynconf address
```

2022-05-30 10:12 UTC, apolukhin approved these changes

2022-05-30 10:25 UTC, merged